# Generated by Django 5.0.2 on 2024-03-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
